name: Deploy to environment
on:
  workflow_dispatch:
jobs:
  deploy_into_dev_server:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Login and commands
        uses: appleboy/ssh-action@master
        with:
          host: http://34.228.78.13
          username: ec2-user
          key: ${{ secrets.REACT_SERVER_PRIVATE_KEY }}
          script: |
            sudo docker stop REACT_SERVICE
            sudo docker run -d -p 8080:80 REACT_SERVICE marcosht4/react-app:latest  
    
