name: Continous Integration
on:
  push:
    branches:
      - master   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install
      - name: Pruebas
        run: |
          npm run test 
      - name: Cypress Test
        run: |
          echo "Hola"    
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git
        uses: actions/checkout@v4
      - name: Dependencies and Building
        run: |
          npm install
          npm run build
      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
      - name: QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Generar imagen docker y push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: marcosht4/react-app:latest
