name: Continous Integration
on:
  push:
    branches:
      - master   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          npm install
      - name: Pruebas
        run: |
          npm run test 
      - name: Cypress Test
        run: |
          echo "Hola"    
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git
        uses: actions/checkout@v4
      - name: Dependencies and Building
        run: |
          npm install
          npm run build